### PR TITLE
Added testimonials

### PR DESCRIPTION
**Pull request by Lalit3716**

### CODE REVIEW

**Comment by Rishabh-malhotraa** [comment]
Great work! Can you use [Masonry](https://mui.com/material-ui/react-masonry/#main-content) component instead of the flex box?

**Comment by Lalit3716** [comment]
> Great work! Can you use [Masonry](https://mui.com/material-ui/react-masonry/#main-content) component instead of the flex box?

Thank You! Masonary component is present in @mui/lab library do you want me to install it ?

**Comment by Rishabh-malhotraa** [comment]
We [already](https://github.com/Rishabh-malhotraa/Vita/blob/main/client/package.json#L11) have it installed.

**Comment by Lalit3716** [comment]
> We [already](https://github.com/Rishabh-malhotraa/Vita/blob/main/client/package.json#L11) have it installed.

Oops sorry my bad! My auto import didn't worked that's why I thought it wasn't installed lol 🙂

**Comment by Lalit3716** [comment]
Outdated PR!

**Pull request closed without merging**
