### PR TITLE
Copy room link on click 

### PR DESCRIPTION
**Pull request by yahya-cloud**
Hello,
As earlier there was no option to copy video chat link on click. Now instead of making an another button,
i added the copyLink function to Label onClick event listener, also made the label cursor pointer.

### CODE REVIEW

**Comment by Sahaj-Srivastava24** [comment]
Hey @yahya-cloud, 
Your work looks good to me. Can you add a snackbar notification that pops up when the link is copied?
You can look at [MUI Snackbar](https://mui.com/components/snackbars/) to see how snackbars work.

**Comment by yahya-cloud** [comment]
Hello @Rishabh-malhotraa , yes sure i will add it and can  you please add GGSOC label to this pull request.

**Comment by yahya-cloud** [comment]
hello @Sahaj-Srivastava24, as i saw react-toastify was used in this project so added the toast function inside copy link function, instead of using mui snackbar. Now when we copy the link a toast appears of type success with text "Link copied" .

**Comment by Lalit3716** [comment]
Sorry @yahya-cloud we decided to move Vita-Meet outside from our main app. So we couldn't merge this PR Hope you will understand! 😔

Though thanks for giving us your valuable time, we will look forward to see successful contributions from you!

**Pull request closed without merging**
